import { addDays, startOfWeek, format } from 'date-fns';

const today = new Date();
const startOfCurrentWeek = startOfWeek(today, { weekStartsOn: 1 });

export const mockEmployees = [
  // Servers (5)
  {
    id: 'emp_1',
    name: 'Sarah Jenkins',
    email: 'sarah.j@scallywags.com',
    phone: '+1 (555) 123-4567',
    position: 'Server',
    availability: {
      monday: [{ start: '11:00', end: '04:00' }],
      tuesday: [{ start: '11:00', end: '04:00' }],
      wednesday: [{ start: '11:00', end: '04:00' }],
      thursday: [{ start: '11:00', end: '04:00' }],
      friday: [{ start: '11:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_6',
    name: 'Emma Thompson',
    email: 'emma.t@scallywags.com',
    phone: '+1 (555) 789-0123',
    position: 'Server',
    availability: {
      tuesday: [{ start: '17:00', end: '04:00' }],
      wednesday: [{ start: '17:00', end: '04:00' }],
      thursday: [{ start: '17:00', end: '04:00' }],
      friday: [{ start: '17:00', end: '04:00' }],
      saturday: [{ start: '11:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_7',
    name: 'Daniel Martinelli',
    email: 'daniel.m@scallywags.com',
    phone: '+1 (555) 890-1234',
    position: 'Server',
    availability: {
      monday: [{ start: '17:00', end: '04:00' }],
      wednesday: [{ start: '11:00', end: '04:00' }],
      friday: [{ start: '11:00', end: '04:00' }],
      saturday: [{ start: '17:00', end: '04:00' }],
      sunday: [{ start: '11:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_8',
    name: 'Olivia Chen',
    email: 'olivia.c@scallywags.com',
    phone: '+1 (555) 901-2345',
    position: 'Server',
    availability: {
      tuesday: [{ start: '11:00', end: '04:00' }],
      thursday: [{ start: '11:00', end: '04:00' }],
      friday: [{ start: '17:00', end: '04:00' }],
      saturday: [{ start: '11:00', end: '04:00' }],
      sunday: [{ start: '17:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_9',
    name: 'Marcus Johnson',
    email: 'marcus.j@scallywags.com',
    phone: '+1 (555) 012-3456',
    position: 'Server',
    availability: {
      monday: [{ start: '11:00', end: '04:00' }],
      tuesday: [{ start: '17:00', end: '04:00' }],
      thursday: [{ start: '17:00', end: '04:00' }],
      saturday: [{ start: '11:00', end: '04:00' }],
      sunday: [{ start: '11:00', end: '04:00' }],
    },
  },

  // Bartenders (5)
  {
    id: 'emp_2',
    name: 'Mike Ross',
    email: 'mike.r@scallywags.com',
    phone: '+1 (555) 234-5678',
    position: 'Bartender',
    availability: {
      thursday: [{ start: '16:00', end: '04:00' }],
      friday: [{ start: '16:00', end: '04:00' }],
      saturday: [{ start: '16:00', end: '04:00' }],
      sunday: [{ start: '12:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_10',
    name: 'Sophia Rodriguez',
    email: 'sophia.r@scallywags.com',
    phone: '+1 (555) 123-7890',
    position: 'Bartender',
    availability: {
      monday: [{ start: '17:00', end: '04:00' }],
      wednesday: [{ start: '17:00', end: '04:00' }],
      friday: [{ start: '16:00', end: '04:00' }],
      saturday: [{ start: '16:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_11',
    name: 'James Wilson',
    email: 'james.w@scallywags.com',
    phone: '+1 (555) 234-8901',
    position: 'Bartender',
    availability: {
      tuesday: [{ start: '17:00', end: '04:00' }],
      thursday: [{ start: '16:00', end: '04:00' }],
      friday: [{ start: '16:00', end: '04:00' }],
      saturday: [{ start: '16:00', end: '04:00' }],
      sunday: [{ start: '12:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_12',
    name: 'Isabella Garcia',
    email: 'isabella.g@scallywags.com',
    phone: '+1 (555) 345-9012',
    position: 'Bartender',
    availability: {
      monday: [{ start: '17:00', end: '04:00' }],
      tuesday: [{ start: '17:00', end: '04:00' }],
      wednesday: [{ start: '17:00', end: '04:00' }],
      saturday: [{ start: '16:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_13',
    name: 'Ethan Brown',
    email: 'ethan.b@scallywags.com',
    phone: '+1 (555) 456-0123',
    position: 'Bartender',
    availability: {
      wednesday: [{ start: '17:00', end: '04:00' }],
      thursday: [{ start: '16:00', end: '04:00' }],
      friday: [{ start: '16:00', end: '04:00' }],
      saturday: [{ start: '16:00', end: '04:00' }],
      sunday: [{ start: '12:00', end: '04:00' }],
    },
  },

  // Managers (5)
  {
    id: 'emp_3',
    name: 'Jessica Pearson',
    email: 'jessica.p@scallywags.com',
    phone: '+1 (555) 345-6789',
    position: 'Manager',
    availability: {
      monday: [{ start: '10:00', end: '20:00' }],
      tuesday: [{ start: '10:00', end: '20:00' }],
      wednesday: [{ start: '10:00', end: '20:00' }],
      thursday: [{ start: '10:00', end: '20:00' }],
      friday: [{ start: '10:00', end: '20:00' }],
    },
  },
  {
    id: 'emp_14',
    name: 'Alexander Lee',
    email: 'alex.l@scallywags.com',
    phone: '+1 (555) 567-1234',
    position: 'Manager',
    availability: {
      tuesday: [{ start: '14:00', end: '04:00' }],
      wednesday: [{ start: '14:00', end: '04:00' }],
      thursday: [{ start: '14:00', end: '04:00' }],
      friday: [{ start: '14:00', end: '04:00' }],
      saturday: [{ start: '10:00', end: '04:00' }],
    },
  },
  {
    id: 'emp_15',
    name: 'Victoria Davis',
    email: 'victoria.d@scallywags.com',
    phone: '+1 (555) 678-2345',
    position: 'Manager',
    availability: {
      monday: [{ start: '14:00', end: '00:00' }],
      wednesday: [{ start: '14:00', end: '00:00' }],
      friday: [{ start: '10:00', end: '20:00' }],
      saturday: [{ start: '10:00', end: '04:00' }],
      sunday: [{ start: '10:00', end: '20:00' }],
    },
  },
  {
    id: 'emp_16',
    name: 'Christopher Taylor',
    email: 'chris.t@scallywags.com',
    phone: '+1 (555) 789-3456',
    position: 'Manager',
    availability: {
      monday: [{ start: '10:00', end: '20:00' }],
      tuesday: [{ start: '10:00', end: '20:00' }],
      thursday: [{ start: '14:00', end: '04:00' }],
      saturday: [{ start: '14:00', end: '04:00' }],
      sunday: [{ start: '10:00', end: '20:00' }],
    },
  },
  {
    id: 'emp_17',
    name: 'Natalie Anderson',
    email: 'natalie.a@scallywags.com',
    phone: '+1 (555) 890-4567',
    position: 'Manager',
    availability: {
      tuesday: [{ start: '10:00', end: '20:00' }],
      wednesday: [{ start: '10:00', end: '20:00' }],
      friday: [{ start: '14:00', end: '04:00' }],
      saturday: [{ start: '10:00', end: '04:00' }],
      sunday: [{ start: '10:00', end: '20:00' }],
    },
  },

  // Kitchen Staff (5)
  {
    id: 'emp_4',
    name: 'Louis Litt',
    email: 'louis.l@scallywags.com',
    phone: '+1 (555) 456-7890',
    position: 'Kitchen',
    availability: {
      monday: [{ start: '10:00', end: '00:00' }],
      wednesday: [{ start: '10:00', end: '00:00' }],
      friday: [{ start: '10:00', end: '02:00' }],
      saturday: [{ start: '10:00', end: '02:00' }],
    },
  },
  {
    id: 'emp_18',
    name: 'Miguel Santos',
    email: 'miguel.s@scallywags.com',
    phone: '+1 (555) 901-5678',
    position: 'Kitchen',
    availability: {
      tuesday: [{ start: '10:00', end: '00:00' }],
      wednesday: [{ start: '10:00', end: '00:00' }],
      thursday: [{ start: '10:00', end: '00:00' }],
      friday: [{ start: '10:00', end: '02:00' }],
      saturday: [{ start: '10:00', end: '02:00' }],
    },
  },
  {
    id: 'emp_19',
    name: 'Amy Wu',
    email: 'amy.w@scallywags.com',
    phone: '+1 (555) 012-6789',
    position: 'Kitchen',
    availability: {
      monday: [{ start: '10:00', end: '00:00' }],
      tuesday: [{ start: '10:00', end: '00:00' }],
      thursday: [{ start: '10:00', end: '00:00' }],
      saturday: [{ start: '10:00', end: '02:00' }],
      sunday: [{ start: '10:00', end: '00:00' }],
    },
  },
  {
    id: 'emp_20',
    name: 'David Kim',
    email: 'david.k@scallywags.com',
    phone: '+1 (555) 123-7901',
    position: 'Kitchen',
    availability: {
      monday: [{ start: '10:00', end: '00:00' }],
      wednesday: [{ start: '10:00', end: '00:00' }],
      thursday: [{ start: '10:00', end: '00:00' }],
      friday: [{ start: '10:00', end: '02:00' }],
      sunday: [{ start: '10:00', end: '00:00' }],
    },
  },
  {
    id: 'emp_21',
    name: 'Priya Patel',
    email: 'priya.p@scallywags.com',
    phone: '+1 (555) 234-8012',
    position: 'Kitchen',
    availability: {
      tuesday: [{ start: '10:00', end: '00:00' }],
      wednesday: [{ start: '10:00', end: '00:00' }],
      friday: [{ start: '10:00', end: '02:00' }],
      saturday: [{ start: '10:00', end: '02:00' }],
      sunday: [{ start: '10:00', end: '00:00' }],
    },
  },

  // Hosts (5)
  {
    id: 'emp_5',
    name: 'Rachel Zane',
    email: 'rachel.z@scallywags.com',
    phone: '+1 (555) 567-8901',
    position: 'Host',
    availability: {
      friday: [{ start: '17:00', end: '02:00' }],
      saturday: [{ start: '11:00', end: '02:00' }],
      sunday: [{ start: '11:00', end: '02:00' }],
    },
  },
  {
    id: 'emp_22',
    name: 'Lily Chang',
    email: 'lily.c@scallywags.com',
    phone: '+1 (555) 345-9123',
    position: 'Host',
    availability: {
      monday: [{ start: '17:00', end: '00:00' }],
      tuesday: [{ start: '17:00', end: '00:00' }],
      thursday: [{ start: '17:00', end: '02:00' }],
      friday: [{ start: '17:00', end: '02:00' }],
      saturday: [{ start: '11:00', end: '02:00' }],
    },
  },
  {
    id: 'emp_23',
    name: 'Ryan Murphy',
    email: 'ryan.m@scallywags.com',
    phone: '+1 (555) 456-0234',
    position: 'Host',
    availability: {
      wednesday: [{ start: '17:00', end: '00:00' }],
      thursday: [{ start: '17:00', end: '02:00' }],
      friday: [{ start: '17:00', end: '02:00' }],
      saturday: [{ start: '11:00', end: '02:00' }],
      sunday: [{ start: '11:00', end: '02:00' }],
    },
  },
  {
    id: 'emp_24',
    name: 'Grace Foster',
    email: 'grace.f@scallywags.com',
    phone: '+1 (555) 567-1345',
    position: 'Host',
    availability: {
      monday: [{ start: '17:00', end: '00:00' }],
      tuesday: [{ start: '17:00', end: '00:00' }],
      wednesday: [{ start: '17:00', end: '00:00' }],
      friday: [{ start: '17:00', end: '02:00' }],
      sunday: [{ start: '11:00', end: '02:00' }],
    },
  },
  {
    id: 'emp_25',
    name: 'Noah Bennett',
    email: 'noah.b@scallywags.com',
    phone: '+1 (555) 678-2456',
    position: 'Host',
    availability: {
      tuesday: [{ start: '17:00', end: '00:00' }],
      wednesday: [{ start: '17:00', end: '00:00' }],
      thursday: [{ start: '17:00', end: '02:00' }],
      saturday: [{ start: '11:00', end: '02:00' }],
      sunday: [{ start: '11:00', end: '02:00' }],
    },
  },
];

// Generate comprehensive shifts for the current week based on 11am-4am hours
export const mockShifts = [
  // Monday
  {
    id: 'shift_1',
    employeeId: 'emp_1',
    employeeName: 'Sarah Jenkins',
    position: 'Server',
    date: format(addDays(startOfCurrentWeek, 0), 'yyyy-MM-dd'),
    startTime: '11:00',
    endTime: '19:00',
    notes: 'Day shift',
  },
  {
    id: 'shift_2',
    employeeId: 'emp_3',
    employeeName: 'Jessica Pearson',
    position: 'Manager',
    date: format(addDays(startOfCurrentWeek, 0), 'yyyy-MM-dd'),
    startTime: '10:00',
    endTime: '18:00',
    notes: 'Opening Manager',
  },
  {
    id: 'shift_3',
    employeeId: 'emp_4',
    employeeName: 'Louis Litt',
    position: 'Kitchen',
    date: format(addDays(startOfCurrentWeek, 0), 'yyyy-MM-dd'),
    startTime: '11:00',
    endTime: '20:00',
    notes: 'Lunch/Dinner prep',
  },

  // Tuesday
  {
    id: 'shift_4',
    employeeId: 'emp_1',
    employeeName: 'Sarah Jenkins',
    position: 'Server',
    date: format(addDays(startOfCurrentWeek, 1), 'yyyy-MM-dd'),
    startTime: '19:00',
    endTime: '03:00',
    notes: 'Late night',
  },
  {
    id: 'shift_5',
    employeeId: 'emp_3',
    employeeName: 'Jessica Pearson',
    position: 'Manager',
    date: format(addDays(startOfCurrentWeek, 1), 'yyyy-MM-dd'),
    startTime: '14:00',
    endTime: '22:00',
    notes: 'Mid shift',
  },

  // Wednesday
  {
    id: 'shift_6',
    employeeId: 'emp_4',
    employeeName: 'Louis Litt',
    position: 'Kitchen',
    date: format(addDays(startOfCurrentWeek, 2), 'yyyy-MM-dd'),
    startTime: '16:00',
    endTime: '00:00',
    notes: 'Dinner service',
  },
  {
    id: 'shift_7',
    employeeId: 'emp_1',
    employeeName: 'Sarah Jenkins',
    position: 'Server',
    date: format(addDays(startOfCurrentWeek, 2), 'yyyy-MM-dd'),
    startTime: '11:00',
    endTime: '19:00',
    notes: 'Day shift',
  },
  {
    id: 'shift_8',
    employeeId: 'emp_3',
    employeeName: 'Jessica Pearson',
    position: 'Manager',
    date: format(addDays(startOfCurrentWeek, 2), 'yyyy-MM-dd'),
    startTime: '10:00',
    endTime: '18:00',
    notes: '',
  },

  // Thursday
  {
    id: 'shift_9',
    employeeId: 'emp_2',
    employeeName: 'Mike Ross',
    position: 'Bartender',
    date: format(addDays(startOfCurrentWeek, 3), 'yyyy-MM-dd'),
    startTime: '20:00',
    endTime: '04:00',
    notes: 'Closing bar',
  },
  {
    id: 'shift_10',
    employeeId: 'emp_1',
    employeeName: 'Sarah Jenkins',
    position: 'Server',
    date: format(addDays(startOfCurrentWeek, 3), 'yyyy-MM-dd'),
    startTime: '18:00',
    endTime: '02:00',
    notes: 'Evening shift',
  },
  {
    id: 'shift_11',
    employeeId: 'emp_3',
    employeeName: 'Jessica Pearson',
    position: 'Manager',
    date: format(addDays(startOfCurrentWeek, 3), 'yyyy-MM-dd'),
    startTime: '12:00',
    endTime: '20:00',
    notes: '',
  },

  // Friday
  {
    id: 'shift_12',
    employeeId: 'emp_1',
    employeeName: 'Sarah Jenkins',
    position: 'Server',
    date: format(addDays(startOfCurrentWeek, 4), 'yyyy-MM-dd'),
    startTime: '19:00',
    endTime: '04:00',
    notes: 'Busy night close',
  },
  {
    id: 'shift_13',
    employeeId: 'emp_2',
    employeeName: 'Mike Ross',
    position: 'Bartender',
    date: format(addDays(startOfCurrentWeek, 4), 'yyyy-MM-dd'),
    startTime: '20:00',
    endTime: '04:00',
    notes: 'Closing bar',
  },
  {
    id: 'shift_14',
    employeeId: 'emp_5',
    employeeName: 'Rachel Zane',
    position: 'Host',
    date: format(addDays(startOfCurrentWeek, 4), 'yyyy-MM-dd'),
    startTime: '18:00',
    endTime: '02:00',
    notes: 'Evening host',
  },
  {
    id: 'shift_15',
    employeeId: 'emp_4',
    employeeName: 'Louis Litt',
    position: 'Kitchen',
    date: format(addDays(startOfCurrentWeek, 4), 'yyyy-MM-dd'),
    startTime: '16:00',
    endTime: '02:00',
    notes: 'Late night food',
  },
  {
    id: 'shift_16',
    employeeId: 'emp_3',
    employeeName: 'Jessica Pearson',
    position: 'Manager',
    date: format(addDays(startOfCurrentWeek, 4), 'yyyy-MM-dd'),
    startTime: '16:00',
    endTime: '02:00',
    notes: 'Closing manager',
  },

  // Saturday
  {
    id: 'shift_17',
    employeeId: 'emp_2',
    employeeName: 'Mike Ross',
    position: 'Bartender',
    date: format(addDays(startOfCurrentWeek, 5), 'yyyy-MM-dd'),
    startTime: '20:00',
    endTime: '04:00',
    notes: 'Saturday night fever',
  },
  {
    id: 'shift_18',
    employeeId: 'emp_5',
    employeeName: 'Rachel Zane',
    position: 'Host',
    date: format(addDays(startOfCurrentWeek, 5), 'yyyy-MM-dd'),
    startTime: '11:00',
    endTime: '19:00',
    notes: 'Day host',
  },
  {
    id: 'shift_19',
    employeeId: 'emp_4',
    employeeName: 'Louis Litt',
    position: 'Kitchen',
    date: format(addDays(startOfCurrentWeek, 5), 'yyyy-MM-dd'),
    startTime: '12:00',
    endTime: '22:00',
    notes: 'All day prep',
  },

  // Sunday
  {
    id: 'shift_20',
    employeeId: 'emp_2',
    employeeName: 'Mike Ross',
    position: 'Bartender',
    date: format(addDays(startOfCurrentWeek, 6), 'yyyy-MM-dd'),
    startTime: '12:00',
    endTime: '20:00',
    notes: 'Sunday Funday',
  },
  {
    id: 'shift_21',
    employeeId: 'emp_5',
    employeeName: 'Rachel Zane',
    position: 'Host',
    date: format(addDays(startOfCurrentWeek, 6), 'yyyy-MM-dd'),
    startTime: '12:00',
    endTime: '20:00',
    notes: '',
  },
];
